apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "salt-enterprise.fullname" . }}
  labels:
    app: {{ include "salt-enterprise.name" . }}
    chart: {{ include "salt-enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ include "salt-enterprise.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "salt-enterprise.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RAAS_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "salt-enterprise.fullname" . }}-secrets
                  key: raas.key
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 120
            timeoutSeconds: 30
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            initialDelaySeconds: 120
            periodSeconds: 120
            timeoutSeconds: 30
            httpGet:
              path: /
              port: 8080
          volumeMounts:
            - mountPath: /var/lib/raas
              name: raas-var-lib-raas
            - mountPath: /etc/raas
              name: raas-etc-raas
            - mountPath: /etc/raas/raas
              name: raas-secrets
              subPath: raas
            - mountPath: /etc/raas/raas.license
              name: raas-secrets
              subPath: raas.license
            - mountPath: /etc/raas/ca_bundle.pem
              name: raas-secrets
              subPath: ca_bundle
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: raas-var-lib-raas
        emptyDir: {}
      - name: raas-etc-raas
        emptyDir: {}
      - name: raas-secrets
        secret:
          defaultMode: 444
          secretName: {{ include "salt-enterprise.fullname" . }}-secrets
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
