apiVersion: v1
kind: Secret
metadata:
  name: {{ include "salt-enterprise.name" . }}-secrets
  labels:
    app: {{ include "salt-enterprise.name" . }}
    chart: {{ include "salt-enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
    raas: {{ .Values.secrets.raas | b64enc }}
    raas.license: {{ .Values.secrets.raas_license }}
    raas.key: {{ .Values.secrets.raas_encryption_key | b64enc }}
    ca_bundle: {{ .Values.secrets.ca_bundle | b64enc }}